name: Classroom Autograding (Unit Tests)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  actions: read

jobs:
  grade:
    runs-on: windows-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      # Build everything once so tests can run with --no-build
      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      # Run tests and capture the exit code for grading
      - name: Run tests
        id: run-tests
        shell: pwsh
        run: |
          dotnet test w3.tests/w3.tests.csproj `
            --configuration Release `
            --no-build `
            --logger "trx;LogFileName=results.trx"
          "exit_code=$LASTEXITCODE" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Upload TRX
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/results.trx'
          if-no-files-found: warn

      # Produce the JSON that GitHub Classroom's reporter expects.
      # IMPORTANT: use the multiline env var syntax (<<EOF ... EOF) so formatting is valid.
      - name: Prepare grading JSON
        shell: pwsh
        run: |
          $passed = ("${{ steps.run-tests.outputs.exit_code }}" -eq "0")
          if ($passed) { $status = "passed"; $score = 100 } else { $status = "failed"; $score = 0 }
          $json = @{ version=1; status="ok"; tests=@(@{ name="Unit Tests"; status=$status; score=$score; max_score=100; execution_time="0s"; message="" }) } | ConvertTo-Json -Compress
          @"
          UNIT-TESTS_RESULTS<<EOF
          $json
          EOF
          "@ | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: unit-tests
        env:
          UNIT-TESTS_RESULTS: ${{ env.UNIT-TESTS_RESULTS }}
