name: Autograding
on:
  push:
  workflow_dispatch:
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  grade:
    if: github.actor != 'github-classroom[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore

      # Use exit code only; no stdin expectations, no regex matching.
      - name: Run unit tests (exit code grading)
        id: unit-tests
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Unit Tests
          command: dotnet test w3.tests/w3.tests.csproj --configuration Release --no-build --logger "trx;LogFileName=results.trx"
          timeout: 600
          max-score: 100

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: unit-tests
        env:
          UNIT-TESTS_RESULTS: "${{ steps.unit-tests.outputs.result }}"
