name: Autograding

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  grade:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test and create results file
        shell: pwsh
        run: |
          dotnet test w3.tests/w3.tests.csproj `
            --configuration Release `
            --no-build `
            --logger "trx;LogFileName=results.trx"

          if ($LASTEXITCODE -eq 0) {
            $status = "passed"; $score = 100
          } else {
            $status = "failed"; $score = 0
          }

          $json = @{
            version = 1
            status  = "ok"
            tests   = @(@{
              name           = "Unit Tests"
              status         = $status
              score          = $score
              max_score      = 100
              execution_time = "0s"
              message        = ""
            })
          } | ConvertTo-Json -Compress

          $json | Out-File -Encoding utf8 test-results.json

      - name: Upload test results (TRX + JSON)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/results.trx
            test-results.json

      - name: Report grades to GitHub Classroom
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          results: test-results.json
          token: ${{ secrets.GITHUB_TOKEN }}
