name: Autograding

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  grade:
    runs-on: windows-2022
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore
        shell: pwsh

      - name: Build
        run: dotnet build --configuration Release --no-restore
        shell: pwsh

      - name: Test and capture TRX
        id: unit
        shell: pwsh
        run: |
          dotnet test w3.tests/w3.tests.csproj `
            --configuration Release `
            --no-build `
            --logger "trx;LogFileName=results.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/results.trx"

      - name: Prepare autograder env
        shell: pwsh
        run: |
          if ($LASTEXITCODE -eq 0) { $status = "passed"; $score = 100 } else { $status = "failed"; $score = 0 }

          $json = @{ 
            version = 1
            status  = "ok"
            tests   = @(@{
              name           = "Unit Tests"
              status         = $status
              score          = $score
              max_score      = 100
              execution_time = "0s"
              message        = ""
            })
          } | ConvertTo-Json -Compress

          "unit_RESULTS=$json" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Report grades
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: "unit"
          token: ${{ secrets.GITHUB_TOKEN }}
